"""Initial migration

Revision ID: 30aaa8d1b0a0
Revises: 
Create Date: 2025-11-30 15:15:22.284705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30aaa8d1b0a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('muscle_group',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.drop_column('equipment')
        batch_op.drop_column('calories_per_minute')
        batch_op.drop_column('instructions')
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.alter_column('body_fat',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('body_fat_percentage')
        batch_op.drop_column('mood')
        batch_op.drop_column('energy_level')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('experience_level')
        batch_op.drop_column('daily_calorie_goal')

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('calories_burned')

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_calorie_goal', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_level', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('body_fat_percentage', sa.FLOAT(), nullable=True))
        batch_op.alter_column('body_fat',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('calories_per_minute', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('equipment', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('muscle_group',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
