"""second migrate

Revision ID: 53a7361b2ff0
Revises: c358a04d6cdc
Create Date: 2025-11-24 19:55:37.088563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a7361b2ff0'
down_revision = 'c358a04d6cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calories_per_minute', sa.Float(), nullable=True))

    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_fat_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('energy_level', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('daily_calorie_goal', sa.Integer(), nullable=True))

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned', sa.Float(), nullable=True))

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('workout_type')

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('calories_burned')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_calorie_goal')
        batch_op.drop_column('experience_level')

    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.drop_column('energy_level')
        batch_op.drop_column('mood')
        batch_op.drop_column('body_fat_percentage')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('calories_per_minute')
        batch_op.drop_column('instructions')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('equipment')

    # ### end Alembic commands ###
